name: Linux

on: [push, pull_request]

jobs:
  build:
    name: GCC-${{matrix.build_type}}-${{matrix.lib}}-${{matrix.components}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        build_type: [Release, Debug]
        lib: [shared, static]
        components: [minimal, lgpl, gpl]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Dependencies
      shell: bash
      run: |
        sudo apt-get update
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
          build-essential \
          cmake \
          gfortran \
          libblas-dev \
          liblapack-dev \
          libmetis-dev \
          libomp-dev \
          libtbb-dev \
          ninja-build \
          nvidia-cuda-toolkit

    - name: Configure
      shell: bash
      run: |
        cmake -S . -B build_${{matrix.build_type}}/ \
              -G Ninja \
              -DBUILD_SHARED_LIBS=$([[ ${{matrix.lib}} == static ]] && echo OFF || echo ON) \
              -DWITH_GPL=$([[ ${{matrix.components}} != gpl ]] && echo OFF || echo ON) \
              -DWITH_LGPL=$([[ ! ${{matrix.components}} =~ gpl ]] && echo OFF || echo ON)
    - name: Build
      shell: bash
      run: |
        cmake --build build_${{matrix.build_type}}/ \
              --config ${{matrix.build_type}}
